CREATE DATABASE IF NOT EXISTS appdb;
USE appdb;

CREATE TABLE IF NOT EXISTS SECRETS (
	filename VARCHAR(64),
	secret VARCHAR(64) 
);

REVOKE ALL PRIVILEGES ON appdb.* FROM 'example-user'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE ON appdb.SECRETS TO 'example-user'@'%';
FLUSH PRIVILEGES;
