services:
  website:
    build:
      context: ./website
    container_name: lain-web
    ports:
      - "8888:5000"
    environment:
      MARIADB_HOST: mariadb
      MARIADB_USER: example-user
      MARIADB_PASSWORD: my_cool_secret
      MARIADB_DATABASE: appdb
    networks:
      - labnet
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
      - apparmor:lain-container
    restart: unless-stopped
    depends_on:
      - mariadb
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M


  mariadb:
    build:
      context: ./mariadb
    container_name: lain-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: changeme123
      MARIADB_USER: example-user
      MARIADB_PASSWORD: my_cool_secret
      MARIADB_DATABASE: appdb
    networks:
      - labnet
    cap_drop:
      - ALL
    cap_add:
     - CHOWN
     - DAC_OVERRIDE
     - FOWNER
     - SETUID
     - SETGID
     - KILL
    security_opt:
      - apparmor:lain-container
    restart: unless-stopped
    init: true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1512M
    volumes:
      - ./hardening.cnf:/etc/mysql/conf.d/hardening.cnf:ro
      - ./mariadb/init/01-grants.sql:/docker-entrypoint-initdb.d/01-grants.sql:ro

networks:
  labnet:
    driver: bridge

